### ISSUE TITLE
Add the requirement file instead of specifying that in README

### ISSUE THREAD

**Issue by FuyukiSakura** [AriBowe/orb#1]
The `requirement.txt` file includes the dependency that needs to be installed.
A sample of `requirement.txt` is as follow:
```
# Discord (Of course)
discord.py==1.1.1
```
Contributors can then run `pip install -r requirements.txt` to install the dependencies.

You can checkout #2 for the fix and with more git basics.

**Comment by AriBowe** [comment]
Added requirements
